`fix`: move alignment to its own subworkflow to prevent main workflow to long:
nextflow.exception.ScriptCompilationException: Module compilation error
- file : /crepas/workflows/crepas/main.nf
- cause:: -1: String too long. The given string is 65561 Unicode code units long, but only a maximum of 65535 is allowed.
 @ line -1, column -1.